version: '3.8'
services:
  ouranos-server:
    container_name: ouranos
    build:
      context: ../
      dockerfile: ouranos-docker/Dockerfile
    image: ouranos:latest
    command:
      - "--dev"
      - "--version"
      - "--debug"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JAVA_OPTS=-Ddebug -Xmx128m -Dquarkus.http.port=8080
    restart: "no"
    volumes:
      - E:\Developpement\Workspace\eclipse\log:/var/log/ouranos