quarkus:
  micrometer:
    binder-enabled-default: true
    binder:
      http-server:
        ignore-patterns: '/q.*'
  http:
    cors: true
  log:
    file:
      enable: true
      format: "%d{HH:mm:ss.SSS} %-5p [%c{2.}]] (%t) %s%e%n"
      level: INFO
  banner:
    path: banner.txt
  cache:
    enabled: true
    caffeine:
      metrics-enabled: true
      cartesian-position:
        initial-capacity: 10
        maximum-size: 20
        expire-after-write: 900S

sp3:
  authorized-download: true

default:
  sp3:
    directory: /opt/ouranos/sp3
  products:
    access:
      ftp-server-name: igs.ign.fr
      epoch-directory: /pub/igs/products
  elevation:
    mask:
      elevation-mask-degree: 10