server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    excluded-user-agents:
    mime-types: application/json,application/xml
    min-response-size: 2048

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: health,info,metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always

info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifact: @project.artifactId@
    description: SpringBoot application Rest-Api project Ouranos
  build:
    version: @project.version@